name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: apt-get update
        run: sudo apt-get update -y

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: install
        run: ./scripts/install.sh

      - name: build
        run: ./scripts/build.sh

      - name: publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: ./scripts/publish.sh
